### ISSUE TITLE
libXGL_DPP.so.3.7.19 depends on python2 , not available on RHEL/CentOS 9

### ISSUE THREAD

**Issue by tguruswamy** [epics-modules/Dante#29]
The distributed vendor library libXGL_DPP.so is linked against libpython2.7 (despite commit messages saying otherwise), which is not easily available on RHEL9/CentOS9. Is there an update/alternative available?

```
$ ldd -r libXGL_DPP.so.3.7.19 
	linux-vdso.so.1 (0x00007ffe8cdca000)
	libpython2.7.so.1.0 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f301b650000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f301b64b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f301b646000)
	libusb-1.0.so.0 => /lib64/libusb-1.0.so.0 (0x00007f301b627000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f301b54a000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f301b52f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f301b200000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f301c101000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f301b4fe000)
```

commit 8551692172cbb2ea9f4d7d5b4c574c7fe63fe155 (HEAD -> master, origin/master, origin/HEAD)

**Comment by MarkRivers** [comment]
I had XGLAB make available the latest release of their software, DANTE-2.0.8.9 today.  I have downloaded and extracted the files from that for Linux and Windows.  They are now in danteSupport, and uploaded on the master branch.  I have tested that it compiles OK on CentOS 9 Stream and Windows 10.  I have not tested that it acquires OK.  It looks like the HR firmware in that distribution is from 2021, but the LE is from 2023 so that may need to be loaded onto the hardware before running.

**Comment by MarkRivers** [comment]
I used the version of the Linux library that does not depend on Python, so that is no longer an issue.

**Comment by tguruswamy** [comment]
Great, thanks Mark and XGLAB. Will test and report back.

**Comment by tguruswamy** [comment]
I tested a Dante1 (fw version 4.1.3.1) with RHEL9.2 . Basic operation looks good.

The older version of the library (3.7.19) is still being installed to lib/ by the Makefile, but the binary was linked against the correct version (.so.1 -> .so.3.7) which does not depend on python2.

**Comment by MarkRivers** [comment]
I fixed the Makefile so it installs the new version of the library (3.7).  It was working with the old version because soft links are not preserved when building EPICS, so it copied the correct file.
